'use strict';

/**
 * "Generated by" provenance header for created configs (C3 / Q28) and the reverse lookup
 * used by collision detection (Q29). Pure: no `vscode` import, no I/O.
 *
 * Format (YAML comments — ignored by every UMLGen loader):
 *
 *   # Generated by UMLMark 1.0.8 — Create UMLGen Sequence Config
 *   # Created: 2026-10-04T23:10:00Z
 *   # Source selection:
 *   #   - adapters/htmlclean/engine.py
 *   # Entry: adapters/htmlclean/engine.py:HtmlCleaningEngine.clean
 */

import { parse } from 'yaml';

const HEADER_TITLE = '# Generated by UMLMark';
const SOURCES_LABEL = '# Source selection:';
const SOURCE_ITEM_RE = /^#\s+-\s+(.+?)\s*$/;

export interface HeaderInfo {
    readonly version: string;
    readonly commandTitle: string;
    readonly createdIso: string;
    readonly sources: readonly string[];
    readonly entryRule?: string;
}

/** Header lines (without trailing blank line); the patcher prepends them to the template */
export function buildHeaderLines(info: HeaderInfo): string[] {
    return [
        `${HEADER_TITLE} ${info.version} — ${info.commandTitle}`,
        `# Created: ${info.createdIso}`,
        SOURCES_LABEL,
        ...info.sources.map(s => `#   - ${s}`),
        ...(info.entryRule ? [`# Entry: ${info.entryRule}`] : []),
    ];
}

/** First "Source selection" entry of a UMLMark header, if the text carries one */
function headerSource(lines: readonly string[]): string | undefined {
    if (!lines.some(l => l.startsWith(HEADER_TITLE))) { return undefined; }
    const labelIndex = lines.findIndex(l => l.trim() === SOURCES_LABEL);
    const match = labelIndex < 0 ? null : SOURCE_ITEM_RE.exec(lines[labelIndex + 1] ?? '');
    return match ? match[1] : undefined;
}

/**
 * File part of the first `include:` rule, for hand-written / pre-header configs.
 * Only path-like rules count (they contain "/" or end with a source extension);
 * class names and regexes give no file identity.
 */
function firstIncludeFile(text: string): string | undefined {
    try {
        const data = parse(text) as { include?: unknown } | null;
        const first = Array.isArray(data?.include) ? data?.include[0] : undefined;
        if (typeof first !== 'string') { return undefined; }
        const filePart = first.split(':')[0].trim();
        return /\/|\.(py|java|ts)$/.test(filePart) ? filePart : undefined;
    } catch {
        return undefined;
    }
}

/**
 * Source recorded in an existing config (Q29 step 1): header first, then the first include rule.
 * undefined = provenance unknown (caller treats it as "same source" and never overwrites).
 */
export function readConfigSource(text: string): string | undefined {
    return headerSource(text.split(/\r?\n/)) ?? firstIncludeFile(text);
}
